version: 2.1
orbs:
  cypress: cypress-io/cypress@2
workflows:
  build:
    jobs:
      - cypress/install:
          working_directory: site/gatsby-site
          context: staging
          install-command: npm ci --legacy-peer-deps
          build: npm run build
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "site/gatsby-site/package-lock.json"}}
      - cypress/run:
          working_directory: site/gatsby-site
          cache-key: >-
            cache-{{ arch }}-{{ .Branch }}-{{ checksum "site/gatsby-site/package-lock.json"}}
          context: staging
          requires:
            - cypress/install
          record: true
          parallel: true
          parallelism: 3
          group: 3x