name: Process Briefing Notifications - Staging

on:
  schedule:
    - cron: '0 15 * * 0'  # Runs every Sunday at 15:00 UTC
  workflow_dispatch:

jobs:
  call-briefing:
    uses: ./.github/workflows/process-briefing-notifications.yml
    secrets: inherit
    with:
      environment: staging
