name: Deploy staging branch to Empty env 

on:
  push:
    branches:
      - staging

jobs:

  call-test-build:
    uses: ./.github/workflows/test-build.yml
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: empty

  call-test:
    uses: ./.github/workflows/test.yml
    needs: call-test-build
    secrets: inherit
    with:
      sha: ${{ github.sha }}
      environment: empty

  call-deploy:
    uses: ./.github/workflows/deploy.yml
    needs: call-test
    secrets: inherit
    permissions:
      pull-requests: write
    with:
      environment: empty
      sha: ${{ github.sha }}
      netlify-context: deploy-preview # prevent migrations from running
      netlify-alias: 
