name: Realm Deploy Staging

on:
  push:
    branches:
      - staging

jobs:
  push:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - uses: actions/checkout@v2
      - name: "Install the Realm CLI"
        run: |
          npm install -g mongodb-realm-cli
      - name: Login
        run: |
          realm-cli login --api-key="${{ secrets.REALM_API_PUBLIC_KEY }}" --private-api-key="${{ secrets.REALM_API_PRIVATE_KEY }}" --realm-url https://realm.mongodb.com --atlas-url https://cloud.mongodb.com
      - name: Push
        run: |
          cd site/realm
          realm-cli push --remote="${{ secrets.GATSBY_REALM_APP_ID }}" -y

