name: Deploy Staging

on:
  push:
    branches:
      - run-tests-on-github

jobs:
  # call-realm:
  #   uses: ./.github/workflows/realm.yml
  #   secrets: inherit
  #   with:
  #     environment: staging
  call-deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
    with:
      environment: staging
    # needs: call-realm
