name: Translate Reports

on:
  workflow_dispatch:
  schedule:
    - cron: "0 8 * * *" # Run every day at 8 AM

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install NPM dependencies
        run: npm ci
        working-directory: site/gatsby-site

      - name: Run translation script
        run: node src/scripts/translateReports.js
        working-directory: site/gatsby-site
        env:
          MONGODB_TRANSLATIONS_CONNECTION_STRING: ${{ secrets.MONGODB_TRANSLATIONS_CONNECTION_STRING }}
          GOOGLE_TRANSLATE_API_KEY: ${{ secrets.GOOGLE_TRANSLATE_API_KEY }}
          GATSBY_AVAILABLE_LANGUAGES: ${{ vars.GATSBY_AVAILABLE_LANGUAGES }}
          TRANSLATE_SUBMISSION_DATE_START: ${{ vars.TRANSLATE_SUBMISSION_DATE_START }}
          TRANSLATE_DRY_RUN: ${{ vars.TRANSLATE_DRY_RUN }}

